### ISSUE TITLE
Error in deploy command results in parse error

### ISSUE THREAD

**Issue by ShelbyZ** [twilio-labs/twilio-run#131]
https://github.com/twilio-labs/twilio-run/blob/966a08900b04085609c90200cf1b67708425190e/src/commands/deploy.ts#L64-L66

While running the deploy command with a poorly-named service, underscores not allowed, the resulting error seen relates to a parse error on the above lines as it appears that the body parameter is already an object.

```
SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at handleError (/mnt/DAS_MAIN/PRFT/default_repo/source/twilio/node_modules/twilio-run/dist/commands/deploy.js:54:35)
    at Object.<anonymous> (/mnt/DAS_MAIN/PRFT/default_repo/source/twilio/node_modules/twilio-run/dist/commands/deploy.js:108:13)
    at Generator.throw (<anonymous>)
    at rejected (/mnt/DAS_MAIN/PRFT/default_repo/source/twilio/node_modules/twilio-run/dist/commands/deploy.js:6:65)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

![image](https://user-images.githubusercontent.com/1033099/80420118-20c98500-888f-11ea-946b-d569e3fe80e7.png)

**Comment by dkundel** [comment]
This should be fixed with #132 :)
